### ISSUE TITLE
Plugin freezing domoticz

### ISSUE THREAD

**Issue by zozolpl** [sincze/Domoticz-Growatt-Webserver-Plugin#18]
Hello, I installed this plugin, then configured it like on the screen
![image](https://user-images.githubusercontent.com/23475876/146410130-51861900-8c43-49e5-8ea7-1085fa1f79df.png)

When I hit enabled and apply - then domoticz stops working - hardware table is empty, when open devices it says loading in endless loop, other tab like temperature utility etc is empty.

Where Can I find logs of this plugin?
Is there something that could I miss? additional library?

IP is corect - I can reach growatt via browser

To get domoticz working again, need to disable plugin
sudo sqlite3 -header -list domoticz.db "UPDATE Hardware set Enabled = 0 where ID = X"
then restart domoticz

**Comment by zozolpl** [comment]
I made fresh instalation of raspbian, but not bullseye, but buster with python 3.7 instead of 3.9 and it started working

**Comment by sincze** [comment]
Will Close this issue for now.

**Comment by sincze** [comment]
Will Close this issue for now.
