### ISSUE TITLE
502 error and no data

### ISSUE THREAD

**Issue by khunterh** [sincze/Domoticz-Growatt-Webserver-Plugin#2]
Hi,
I've installed your plugin on domoticz running on Synology713+ an get an 502 error.
I've includes the log (I only removed username)  Can you help me ?

[Growattlog.txt](https://github.com/sincze/Domoticz-Growatt-Webserver-Plugin/files/3789779/Growattlog.txt)

**Comment by sincze** [comment]
Mmm 502 means the authentication went wrong.
By accident you posted your password.
As this seemed to be related with your Issue I checked with that pwd and noticed the 502 indeed.
Are you sure username & password are correct?

**Comment by emieldejong** [comment]
I have the same issue and found out the problem. The MD5 hash they use is not a standard one. If the first character of a pair is '0', it should be changed to 'c' (as described here as well: https://github.com/sincze/Domoticz/issues/2#issuecomment-505566334) .

I tested this with `curl -d "password=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&userName=xxxxxx" -H "Content-Type: application/x-www-form-urlencoded" -X POST http://server-api.growatt.com/newTwoLoginAPI.do`

When I have time I'll make a pull request with a fix.

**Comment by sincze** [comment]
Should be fixed now with received pull request.
