### ISSUE TITLE
Change inverter status.

### ISSUE THREAD

**Issue by fgerrits** [sincze/Domoticz-Growatt-Webserver-Plugin#21]
Hi
Is it possible to get the pvstatus from growatt in the script for switching the inverter status.

So when system is online status is On (1)
when system is offline status is Waiting or Off (0)
when the is an error in the system status is Faulty (2)

Now the inverter status does nothing, its 24/7 On

Im running node-red on a seperate RPi there im using another simple growatt function and there i use for the status this.

`
var msg1 = {}; // pvstatus, Inverter run state
switch (msg.payload.values.pvstatus) {
    case 0 :
        msg1.payload = {"command":"udevice","idx":486,"nvalue":0,"svalue": "Waiting"};
    break
    
    case 1 :
        msg1.payload = {"command":"udevice","idx":486,"nvalue":1,"svalue": "Normal"};
    break
    
    case 2 :
        msg1.payload = {"command":"udevice","idx":486,"nvalue":2,"svalue": "Fault"};
    break
}
return [[msg1]];
`

**Comment by sincze** [comment]
If you have node-red running I would like to point out a great new node.

![image](https://github.com/sincze/Domoticz-Growatt-Webserver-Plugin/assets/5776333/58512cf0-42fa-46f1-941a-d9d19695c9ef)

Get's far more data than currently from the plugin.

**Comment by sincze** [comment]
I would use Node-Red.
