### ISSUE TITLE
Growatt Api calls heve changed

### ISSUE THREAD

**Issue by Cees2439867** [sincze/Domoticz-Growatt-Webserver-Plugin#24]
Two days ago at 16:50 data stopped coming on my Domoticz device. No information on internet. On Home Assistant fora I found hint what the issue could be. The API calls where broken.
It used to be http://server-api.growatt.com/newLoginAPI.do
it needs to be from June 14 2022: https://server-api.growatt.com/newTwoLoginAPI.do
Now it seems to work okay again......

**Comment by sincze** [comment]
Need to check that.
For the moment
https://github.com/sincze/Domoticz/blob/master/growatt-inverter.php has a working version.

**Comment by sincze** [comment]
Just installed a new Docker and downloaded the current version from GItHub
![image](https://user-images.githubusercontent.com/5776333/174480341-5b31dbaa-7418-4a37-b207-6245a854f695.png)
I'll need to keep a close eye on it to see if it continues to work.

**Comment by vandermark1977** [comment]
Ik keep having issues lately...
Every 3 minutes this log
`2022-06-20 15:28:03.196 Error: Growatt omvormer: Google returned a status: 502`

**Comment by sincze** [comment]
> Ik keep having issues lately... Every 3 minutes this log `2022-06-20 15:28:03.196 Error: Growatt omvormer: Google returned a status: 502`

And what version are you using of the plugin ?? Usually it takes every 5 minutes for the plugin to do the update.

**Comment by vandermark1977** [comment]
I changed to https in growatt hardware settings and the helped my issue.

**Comment by fgerrits** [comment]
Changing from HTTP to HTTPS in het hardware section in Domoticz (2020.1) worked for me using the old server-api

**Comment by vandermark1977** [comment]
@sincze , tx that helped!

I see the plugin adds values to PVOutput every 2 minutes, why so often? Can this be changed to once every 5 minutes?

![image](https://user-images.githubusercontent.com/49677940/174785261-efdb97df-8a29-43d3-a9f8-7d503bde4c67.png)

**Comment by sincze** [comment]
PVOUTPUT is not supported by me in my plugin. As I had more bug reports
with it than without it ;-)

**Comment by sincze** [comment]
Stale issue closed PVOutput not supported
