### ISSUE TITLE
onMessage: check first the "Status" before getting the "Data" element.

### ISSUE THREAD

**Issue by JoostDkr** [sincze/Domoticz-Growatt-Webserver-Plugin#27]
Last days I received the Python-error "'KeyError': ('Data',)"

I found out that the HTTP response did not contain a lot of data when this error occurred. For example the "Data" element is missing. In that case the status was 588.

The solution to prevent the phyton-error, I moved then line "strData = Data["Data"].decode("utf-8", "ignore")" to under the line "if (Status == 200)".

So if now status 588 is received ( there is no 'data" element) there will be no phyton-error but the plugin report the error.

By the way: at error 400 an 500, the plugin report en Google error. Should be a Growatt error.

**Comment by sincze** [comment]
HI Thank you for your remark.
Do you mean:

```
    def onMessage(self, Connection, Data):
        DumpHTTPResponseToLog(Data)
        Status = int(Data["Status"])
    
        if (Status == 200):
            strData = Data["Data"].decode("utf-8", "ignore")
            LogMessage(strData)
            apiResponse = json.loads(strData)
            Domoticz.Debug("Retrieved following json: "+json.dumps(apiResponse))
```

**Comment by JoostDkr** [comment]
Yep!

**Comment by sincze** [comment]
CLosed and merged
