### ISSUE TITLE
Two sets of the same configuration parameters

### ISSUE THREAD

**Issue by bertinholland** [sincze/Domoticz-Growatt-Webserver-Plugin#31]
I installed de plugin two times. That was my mistake ;-)
But now there are two set of configuration items, see the picture.
How can I fix this and delete one set of patrameters

![image](https://user-images.githubusercontent.com/31294135/202917750-39322774-70f3-4891-8bd5-76c153ff3bb8.png)

**Comment by sincze** [comment]
This is not a plugin issue I guess.
Stop Domoticz
Remove 2nd plugin
Restart Domoticz 
Clear Browser Cache
