### ISSUE TITLE
'back' in apiResponse without 'data' or 'plantId'

### ISSUE THREAD

**Issue by JoostDkr** [sincze/Domoticz-Growatt-Webserver-Plugin#33]
Sometimes I got a Phython-error in the log on line:  self.plantId = apiResponse["back"]["data"][0]["plantId"]
the cause was: the apiResponse contail a 'back' element but no "data" or "plantId". 

In order to prevent this Phython-error, I changed the line " if ('back' in apiResponse):" in "if ('back' in apiResponse and strData.find('data') > -1 and strData.find('plantId') > -1):"

Now i do not receive a Phyton-error any more, instead of that I  got last night a proper exeption: 
Not received anything usefull!: {"back":"503","succes":false}}

**Comment by sincze** [comment]
Thanks for your insights.
So just 1 line change and we are good to go?

OLD: 
```
   try:
                if ('back' in apiResponse):              
                #if not ['back']['success']:
                #    Domoticz.Log("Login Failed")
                #elif ('back' in apiResponse):       
```           

NEW:
```
   try:
                if ('back' in apiResponse and strData.find('data') > -1 and strData.find('plantId') > -1):
                #if not ['back']['success']:
                #    Domoticz.Log("Login Failed")
                #elif ('back' in apiResponse):                  
```

**Comment by JoostDkr** [comment]
Yep!
