### ISSUE TITLE
KeyError: 'Growatt' getting immages from database

### ISSUE THREAD

**Issue by kchiloff** [sincze/Domoticz-Growatt-Webserver-Plugin#35]
Dear,

After last git pull (today)  I started receiving the following, which hampers the plugin from updating.
After checking the DB I could not find table called "Images" , but "CustomImages" instead.  I suspect Domotiz API or DB damodel have changed in the meantime.  Tip: Isolating the below code with try/catch workarounds the issue, so device gets updated, but this is not a solution. 

I hope this feedback helps!   Many thanks for the good work so far!!!!

Best regards,
Chiloff

**The Error**
Feb  4 14:32:42 sentinel domoticz: Growatt:   File "/opt/domoticz/plugins/Domoticz-Growatt-Webserver-Plugin/plugin.py", line 355, in createDevices
Feb  4 14:32:42 sentinel domoticz: Growatt:     image = Images["Growatt"].ID # Get id from database
Feb  4 14:32:42 sentinel domoticz: Growatt: KeyError: 'Growatt'

**Domoticz Context:**
Version: 2022.2
Build Hash: eea9db734
Compile Date: 2022-11-05 13:05:35
dzVents Version: 3.1.8
Python Version: 3.8.10 (default, Jun 22 2022, 20:18:18) [GCC 9.4.0]

**Comment by sincze** [comment]
Can you remove the images from Domoticz as described 

Setup -> More Options - Custom Icons (Remove the Growatt icon) and restart the plugin.

**Comment by sincze** [comment]
No Reaction closing this issue
