### ISSUE TITLE
Growatt Webserver Plug in stopped working

### ISSUE THREAD

**Issue by Cees2439867** [sincze/Domoticz-Growatt-Webserver-Plugin#40]
Hello All,
Just the last two days I am struggling getting the readout of my Growall inverter working again as it shows on the following picture:

![afbeelding](https://github.com/sincze/Domoticz-Growatt-Webserver-Plugin/assets/33065120/e590538c-6458-46fd-b7fc-ee41b813c2cb)
Anyone have an idea or maybe a solution?

**Comment by bmjvannunen** [comment]
I am experiencing the same error since around 8:00 (GMT+2) on Tuesday August 15.
The plugin exits with: Error: Growatt: Growatt returned a status: 405

It seems Growatt has changed the api (login) again.

**Comment by sincze** [comment]
Mmm indeed 15-08-2023 07:55 indeed. Needs investigation guys.

**Comment by tonbor** [comment]
Fine if the updates are minimized so accounts will not be locked anymore.

**Comment by sincze** [comment]
> Fine if the updates are minimized so accounts will not be locked anymore.

Lock outs?? 
Mmm never experienced that with pass2php those run exactly every 5 minutes.

**Comment by tonbor** [comment]
> > Fine if the updates are minimized so accounts will not be locked anymore.
> 
> Lock outs?? Mmm never experienced that with pass2php those run exactly every 5 minutes.

This is the Plug in!

**Comment by sincze** [comment]
> > > Fine if the updates are minimized so accounts will not be locked anymore.
> > 
> > 
> > Lock outs?? Mmm never experienced that with pass2php those run exactly every 5 minutes.
> 
> This is the Plug in!

I got that, hence I use Pass2PhP ;-) , both came from the same guy that has limited amount of time ;-)

**Comment by HarryVerjans** [comment]
> > Fine if the updates are minimized so accounts will not be locked anymore.
> 
> Lock outs?? Mmm never experienced that with pass2php those run exactly every 5 minutes.

I am also having the same issue, but is there an php for Growatt to fetch the data? Where can i find the source?

**Comment by jan-vandenberg** [comment]
I also had this problem, see here: https://www.domoticz.com/forum/viewtopic.php?p=299171#p299171

**Comment by sincze** [comment]
Looked at the APP and did not want to work with me using a proxy in between.
So felt a bit lazy today.
![image](https://github.com/sincze/Domoticz-Growatt-Webserver-Plugin/assets/5776333/84ae7141-05e3-4e3b-89f0-329501017a83)

![image](https://github.com/sincze/Domoticz-Growatt-Webserver-Plugin/assets/5776333/b705d38d-3014-4bbc-b505-f1e9e30f3def)

Solves the issue if you are able to run node-red.

**Comment by Cees2439867** [comment]
Just found out I am writing on the wrong software package, I use growatt-inverter.php. Hoping a lot you will update it? Would be much obliged. Thanks for helping us.

**Comment by sincze** [comment]
For the moment I have the data flowing in via Node-Red.
Now I can have a look at their login mechanism as that was changed.

![image](https://github.com/sincze/Domoticz-Growatt-Webserver-Plugin/assets/5776333/da9ce939-2588-4458-92d0-2acfa2564207)

**Comment by HarryVerjans** [comment]
![image](https://github.com/sincze/Domoticz-Growatt-Webserver-Plugin/assets/72098957/1d8f5fc9-23e1-45ee-8834-304911e415db)
The Growatt Plugin at my brother is not working 100% but much better than my own implementation. I stalled his version on 18 december 2022.

**Comment by sincze** [comment]
The problem is that recently they disabled the old entrypoints for data collection. Now even the app seems more secure ;-) than before.

**Comment by HarryVerjans** [comment]
My own current implementation is accessing too frequently de Api server, that causes a lock out of the web account. As this happens access via Shine Phone is also blocked. Access via webbrowser is in this case no problem. Is there a possibility to limit the access of the plugin to less connections. Is the runagain parameter an option to do this.?

**Comment by sincze** [comment]
> My own current implementation is accessing too frequently de Api server, that causes a lock out of the web account. As this happens access via Shine Phone is also blocked. Access via webbrowser is in this case no problem. Is there a possibility to limit the access of the plugin to less connections. Is the runagain parameter an option to do this.?

published on github so i can have a look?

**Comment by HarryVerjans** [comment]
![image](https://github.com/sincze/Domoticz-Growatt-Webserver-Plugin/assets/72098957/716dab6b-a66c-437d-a6da-09763225ca2a)

At this moment my own implementation of the plugin, that is updated yesterday from github, is running oké. My brothers is stuck, I better did nog mention it was running better. I changed the parameter runagain from 6 to 18 if this is the solution I do not know. In the morning the plugin is struggling in starting up. I wil look in the morning how it is running and report here.

**Comment by oepi-loepi** [comment]
I am developer of a Growatt plugin for the toon thermostat (rooted). This also did stop working some days ago.

Odd thing is that the plugin still works in my qml debugger (Windows) without any problem. Only when i put it in Postman, a curl request or an xml request from a linux device it does give the 405 error.

**Comment by oepi-loepi** [comment]
https://github.com/ToonSoftwareCollective/solarpanel-plugins/blob/main/GROW1.plugin.txt

Deze werkt dus wel in mijn qml debugger maar niet meer op de toon sinds een paar dagen.

**Comment by oepi-loepi** [comment]
I now changed my scripts for toon and is working: First check server server-api.growatt.com. If this gives a 405 error try again but now server.growatt.com

**Comment by HarryVerjans** [comment]
![image](https://github.com/sincze/Domoticz-Growatt-Webserver-Plugin/assets/72098957/822e1653-4a9f-4339-a7e8-198d3030a023)

![image](https://github.com/sincze/Domoticz-Growatt-Webserver-Plugin/assets/72098957/feb466e3-32a4-42a7-af13-e57e4e9ea97f)

At this moment I am getting data every 5 minutes. But as I look at the graphs online and in Domoticz they do not match. Access looks oké but the data from the API is not so accurate. Entrypoint 08:00 08:05 and 08:10 are having the same power value. But for the moment I am happy that there is a working data connection. But changing parameter runagain from 6 to 18 is not the solution, I guess.

**Comment by Cees2439867** [comment]
Yes, just changed three instances of server-api.growatt.com to server.growatt.com in the file growatt-inverter.com and yes it works again:
![afbeelding](https://github.com/sincze/Domoticz-Growatt-Webserver-Plugin/assets/33065120/a9fd62bc-dcc5-453b-8161-79c315de366b)
The values are terrible now. I will change that in the database tomorrow.
So Happy! Thanks to you all, certainly "oepi-loepi" and Sandor of course.

**Comment by Cees2439867** [comment]
Yes, just changed three instances of server-api.growatt.com to server.growatt.com in the file growatt-inverter.php and yes it works again:
![afbeelding](https://github.com/sincze/Domoticz-Growatt-Webserver-Plugin/assets/33065120/a9fd62bc-dcc5-453b-8161-79c315de366b)
The values are terrible now. I will change that in the database tomorrow.
So Happy! Thanks to you all, certainly "oepi-loepi" and Sandor of course.

**Comment by sincze** [comment]
Haha Cees, no PR ;-) 
Let me change to 
server-api.growatt.com to server.growatt.com
in the file.

**Comment by sincze** [comment]
Updated the plugin to 1.0.3 according to the Pass2PHP urls provided by "oepi-loepi" and @Cees2439867

**Comment by tonbor** [comment]
And less updates so no more locks?

**Comment by oepi-loepi** [comment]
@sincze maybe do the double check since they might change server again in future.

**Comment by tonbor** [comment]
Error: Growatt Inverter: (GrowattWeb) failed to load 'plugin.py', Python Path used was '/home/pi/domoticz/plugins/Domoticz-Growatt-Webserver-Plugin/:/usr/lib/python37.zip:/usr/lib/python3.7:/usr/lib/python3.7/lib-dynload:/usr/local/lib/python3.7/dist-packages:/usr/lib/python3/dist-packages:/usr/lib/python3.7/dist-packages'.
2023-08-20 15:57:25.786 Error: Growatt Inverter: Exception: 'SyntaxError'. No traceback available.

**Comment by tonbor** [comment]
after git pull and rename growatt server, not working the latest was working in the evening, not working anymore......

**Comment by HarryVerjans** [comment]
What about the runAgain at line 227 should this also be changed in to 227?
AND
The // in line 84 results in a syntax error # should be used for comments in python ;-)

**Comment by sincze** [comment]
> What about the runAgain at line 227 should this also be changed in to 227?
> AND
> The // in line 84 results in a syntax error # should be used for comments in python ;-)

Crap mixed up python and php.

**Comment by tonbor** [comment]
> 

back to version 1.0.2

**Comment by sincze** [comment]
> > 
> 
> back to version 1.0.2

relax 1 typo and no errorsas mentiones by @HarryVerjans

**Comment by sincze** [comment]
Issue should be solved with latest 1.0.3

**Comment by tonbor** [comment]
2023-08-23 20:19:56.153 Status: Growatt: Initialized version 1.0.4, author 'sincze'
2023-08-23 20:19:56.158 Error: Growatt: Call to function 'onStart' failed, exception details:
2023-08-23 20:19:56.166 Error: Growatt: Traceback (most recent call last):
2023-08-23 20:19:56.166 Error: Growatt: File "/opt/domoticz/userdata/plugins/Domoticz-Growatt-Webserver-Plugin/plugin.py", line 262, in onStart
2023-08-23 20:19:56.166 Error: Growatt: _plugin.onStart()
2023-08-23 20:19:56.166 Error: Growatt: File "/opt/domoticz/userdata/plugins/Domoticz-Growatt-Webserver-Plugin/plugin.py", line 138, in onStart
2023-08-23 20:19:56.166 Error: Growatt: createDevices()
2023-08-23 20:19:56.166 Error: Growatt: File "/opt/domoticz/userdata/plugins/Domoticz-Growatt-Webserver-Plugin/plugin.py", line 351, in createDevices
2023-08-23 20:19:56.166 Error: Growatt: image = Images["Growatt"].ID # Get id from database
2023-08-23 20:19:56.166 Error: Growatt: KeyError: 'Growatt'

**Comment by tonbor** [comment]
no it is not

**Comment by sincze** [comment]
Remove your Growatt icons, that is what the error is all about!

**Comment by tonbor** [comment]
Ok, I did, indeed the plug in is working BUT still a locked Growatt account because of to often access by the plug in.

**Comment by sincze** [comment]
> Ok, I did, indeed the plug in is working BUT still a locked Growatt account because of to often access by the plug in.

mmmm that is interesting... you clocked the five minutes ??? it should trigger every five minutes.
else the 'run again' statement need to be modified twice with higher values.

**Comment by tonbor** [comment]
lockduration 24 
2023-08-24 15:39:16.420 Growatt ***********6;Path=/"]
2023-08-24 15:39:16.420 Growatt Inverter: Data':'b'f"back":
("msg":"507", "lockDuration":"24" success";false]]'
2023-08-24 15:39:16.421 Growatt Inverter: Retrieved following json: ("back": ("msg": "507"
"lockDuration": "24", "success": false)>
2023-08-24 15:39:16.421 Growatt Inverter: Not received anything useful!
2023-08-24 15:39:16.421 Growatt Inverter: Acquiring GIL for 'onMessageCallback'

**Comment by oepi-loepi** [comment]
I have the same if i run multiple instances. E.g 2 toons, domoticz and the app. If i only run 1 instance i do not have this problem.

**Comment by tonbor** [comment]
Would be fine if the update interval could be chosen by the user himself

**Comment by oepi-loepi** [comment]
Not for my toon app since the database runs at 5 minute interval

**Comment by oepi-loepi** [comment]
And you can choose allready in the domoticz plugin if you change the interval in your cron action? So why you need such option?

**Comment by sincze** [comment]
WIth the php file it indeed it is easy to do it in cron (*/5)
the others use the plugin. But PR's are more than welcome.

**Comment by tonbor** [comment]
> 

php is not a plugin
