### ISSUE TITLE
Latest version 1.0.3 not working

### ISSUE THREAD

**Issue by tonbor** [sincze/Domoticz-Growatt-Webserver-Plugin#41]
After git pull :  Error: Growatt Inverter: (GrowattWeb) failed to load 'plugin.py', Python Path used was '/home/pi/domoticz/plugins/Domoticz-Growatt-Webserver-Plugin/:/usr/lib/python37.zip:/usr/lib/python3.7:/usr/lib/python3.7/lib-dynload:/usr/local/lib/python3.7/dist-packages:/usr/lib/python3/dist-packages:/usr/lib/python3.7/dist-packages'.
2023-08-20 16:28:38.144 Error: Growatt Inverter: Exception: 'SyntaxError'. No traceback available.

**Comment by sincze** [comment]
Please try again.

**Comment by sincze** [comment]
Issue Should be solved now for the plugin
