### ISSUE TITLE
Where comes that Google request from?

### ISSUE THREAD

**Issue by differentieel** [sincze/Domoticz-Growatt-Webserver-Plugin#42]
This morning for the first time i got this error:
`2023-08-24 04:18:29.180 Error: Growatt: Google returned a status: 502`
did not happen before

Question: does your code send out Google requests?

If yes; why?
If no; close my request - it must be Growatt Inverter itself

thank you

**Comment by sincze** [comment]
What version do you use
Did you check the plugin code?

**Comment by sincze** [comment]
This should be the only returned code for the plugin.
```
        elif (Status == 400):
            Domoticz.Error("Growatt returned a Bad Request Error.")
        elif (Status == 500):
            Domoticz.Error("Growatt returned a Server Error.")
        else:
            Domoticz.Error("Growatt returned a status: "+str(Status))
```
