### ISSUE TITLE
Plugin not working anymore - API change? 

### ISSUE THREAD

**Issue by alexeyvdlaan** [sincze/Domoticz-Growatt-Webserver-Plugin#9]
Dear, 

the Growatt plugin stopped working since yesterday (21 Sep 2020). I still see that it gets connected, but it obtains only operational status of the convertor and no power information.  I suspect that the API got changed, but cannot get this confirmed. How can we verify that and eventually correct it?

Regards, 
Alexey

**Comment by sincze** [comment]
No Feedback.
Stale, will close this issue for now..
